name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - v*
env:
  LATEST_VERSION: v0.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-test:
    if: ${{ github.event.pull_request }}
    runs-on: ubuntu-latest
    env:
      LOCAL_SITE_DIR: site-pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-render-swagger-plugin
      - run: wget https://raw.githubusercontent.com/harvester/harvester/master/api/openapi-spec/swagger.json -O docs/reference/swagger.json
      - run: mkdocs build
      # https://www.mkdocs.org/user-guide/deploying-your-docs/#local-files
      - name: Modify config for a local site directory
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.site_url = "" | .use_directory_urls = false | del( .plugins[] | select(. == "search") )' mkdocs.yml
      - name: Build a local site directory
        run: mkdocs build -d ${{ env.LOCAL_SITE_DIR }}
      - name: Upload local site directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.LOCAL_SITE_DIR }}
          path: ${{ env.LOCAL_SITE_DIR }}

  master-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike mkdocs-render-swagger-plugin
      - run: |
          git config --global user.name rancherio-gh-m
          git config --global user.email docs@harvesterhci.bot
          git pull
      - run: wget https://raw.githubusercontent.com/harvester/harvester/master/api/openapi-spec/swagger.json -O docs/reference/swagger.json
      - run: |
          mike deploy ${{ env.LATEST_VERSION }}
          mike set-default ${{ env.LATEST_VERSION }}
          mike deploy --rebase --push --update-aliases ${{ env.LATEST_VERSION }} latest

  version-build:
    if: startsWith(github.ref, 'refs/heads/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)"
        id: info
      - run: pip install mkdocs-material mike mkdocs-render-swagger-plugin
      - run: |
          git config --global user.name rancherio-gh-m
          git config --global user.email docs@harvesterhci.bot
          git pull
      - run: wget https://raw.githubusercontent.com/harvester/harvester/master/api/openapi-spec/swagger.json -O docs/reference/swagger.json
      - run: mike deploy --rebase --push ${{ steps.info.outputs.version }}
